config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]

  
  root 'pages#home'
  get 'about' => 'pages#about'
  
  resources :articles
  
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: {minimum: 3, maximum: 20}
  validates :user_id, presence: true
end
  

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum:3, maximum:25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :current_user, :logged_in?

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
  !!current_user
end

def require_user
  if !logged_in?
    flash[:notice]="You need to be logged in"
    redirect_to login_path
  end
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_same_user, only: [:destroy, :edit, :update]
  
  def index
    @articles=Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  
  end
  
  def update
    if @article.update(article_params)
      flash[:success]="Your article was successfully edited"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success]="Your article was successfully saved"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  
  def show
    
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:warning]="This article has been deleted"
  end
  
  
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
     params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:notice]="You may only edit your own articles"
        redirect_to articles_path
      end
    end
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories=Category.all
  end

  def edit
    @category=Category.find(params[:id])
  end
  
  def update
    @category=Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice]="Category Name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end  
  end
  
  def new
    @category=Category.new
  end
  
  def create
    @category=Category.new(category_params)
    if @category.save
      flash[:notice]= "Your category was successfully created"
      redirect_to categories_path
    else
      render 'new'
    end
    
  end
  
  def show
    @category=Category.find(params[:id])
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:notice]="You need to be logged in as admin to create or update a category"
      redirect_to categories_path
    end
  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user=User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      flash[:success]="You are now logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger]="Please re-check your details and try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:success]="You have successfully logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end


  def show
    
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 1)
  end


  def new
    @user = User.new
  end

  
  def edit
    
  end


  def create
    @user = User.new(user_params)

      if @user.save
        session[:user_id]=@user.id
        flash[:notice] = 'Welcome to the Alpha Blog' 
        redirect_to user_path(@user)
      else
        render 'new'
      end
    
  end


  def update
      if @user.update(user_params)
        flash[:notice]= 'User was successfully updated.'
        redirect_to articles_path
      else
        render 'edit'
      end
  end

  
  def destroy
    @user.destroy
    flash[:danger]="The user and all articles relating to the user have been deleted"
    redirect_to users_path

  end

  private
  
    def set_user
      @user = User.find(params[:id])
    end

    
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
    
    
    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:notice]="You may only edit your own account"
        redirect_to users_path
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<% if @article.errors.any? %>

<h2>The following errors prevented the article from being edited</h2>

<ul>

<% @article.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>

<h3> Please edit the article </h3>

<%= form_for @article do |f| %>

<p>
  <%= f.label :title %> <br/>
  <%= f.text_field :title %> 
</p>

<p>
  <%= f.label :description %> <br/>
  <%= f.text_area :description %> 
</p>

<p>
  <%= f.submit %>
</p>

<%end%>

<%= link_to 'Back to Articles Page', articles_path %>

app/views/articles/index.html.erb
<h3 style="color:dimgray; font-size:1.7em; font-weight:bold; text-align:center;">Articles Catalogue</h3></br>
<div align="center">
<%= will_paginate %>
</div>

<% @articles.each do |a| %>
  
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
    <div style="font-size:1.5em; padding-bottom: 10px; padding-top: 50px; text-transform:capitalize;">
    <%= link_to a.title, article_path(a) %>
    </div>
      <div class="indexdesc">
      <%= truncate(a.description, length: 100) %>
        
       
        
        <div class=article-meta-details>
        <small>Created By: <%= a.user.username if a.user %>,
                <%= time_ago_in_words(a.created_at) %> ago</small>
        </div>
      </div>
        
        <% if logged_in? && (current_user==a.user || current_user.admin?) %>
        <div class="article-actions">
        <%= link_to 'Edit', edit_article_path(a), class: "btn btn-xs btn-success" %>
        <%= link_to 'Delete', article_path(a), method: :delete, class: "btn btn-xs btn-danger" %>
        </div>
        <% end %>
        
    </div>
  </div>
  <% end %>
  
  
  <div align="center">
  <%= will_paginate %>
  </div>
  

app/views/articles/new.html.erb
<h3 style="color:dimgray; font-size:1.7em;"> Please create an article </h3></br>

<% if @article.errors.any? %>

<div class="alert alert-danger" role="alert">The following errors prevented the article from getting created</div>

<ul>

<% @article.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

<% end %>

<%= form_for @article do |f| %>

<p>
  <%= f.label :title %> <br/>
  <%= f.text_field :title, placeholder: "Title of Article", autofocus: true %> 
</p>

<p>
  <%= f.label :description %> <br/>
  <%= f.text_area :description, placeholder: "Description of Article", autofocus: true %> 
</p>

<p style="text-transform: capitalize;">
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |x| %>
  <% x.label(class: "checkbox-inline") {x.check_box(class: "checkbox")+ x.text} %>
  <% end %>
</p></br>

<p>
  <%= f.submit class: "btn btn-primary btn-lg" %>
</p></br>

<% end %>

<%= link_to 'Show All Articles', articles_path %>

app/views/articles/show.html.erb
<h3 style="color:dimgray; font-size:1.5em; font-weight:bold"> Article Details </h3><br/>

<p> <div style="font-weight:bold;">Title: </div> <%= @article.title %> </p> 
<p> <div style="font-weight:bold;">Description: </div> <%= simple_format(@article.description) %>
</p>
<p> <div style="font-weight:bold;">Author:</div>  
    <% if @article.user %>
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <% end %>
    
</br>
    <p style="font-weight:bold;">Categories:</p>
    <% if @article.categories.any? %>
    <% @article.categories.each do |a| %>
    <li class="btn btn-xs btn-lg", style="text-transform:capitalize; font-weight:bold;"> <%= link_to a.name, category_path(a) %> </li>
    <% end %>
    <% end %>

      <div style="padding-top: 15px;">
      <%= link_to 'Back to Articles Page', articles_path %> |
      <% if logged_in? && (current_user==@article.user || current_user.admin?) %>
      <%= link_to 'Edit Article', edit_article_path %> |
      </div>
      <% end %>

app/views/categories/edit.html.erb
<h3>Update Category Name</h3></br>

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions", style="padding-top: 10px;">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h3 style="border-bottom: solid 1px grey; margin-bottom: 10px;"> All Categories </h3>

<% @categories.each do |a| %>
  
  <div class="row">
      <div style="font-size:3.2em; padding: 20px 0px 20px 10px; text-transform:capitalize;">
        <%= link_to a.name, category_path(a), class: "btn btn-lg" %>
      </div>
  </div>
<% end %>
        
    

app/views/categories/new.html.erb
<h3> Create a new Category </h3></br>

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h3 style="text-transform:capitalize; color:slategrey; border-bottom: 1px solid grey; padding-bottom: 10px;">Category: <%= @category.name %></h3>

<% if logged_in? && current_user.admin? %>
<%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-success btn-xs" %></br>
<% end %>

<h5 style="font-weight:bold;">List of Articles</h5>

<% if @category.articles.any? %>
<% @category.articles.each do |f| %>
<div class="row">
  <li class="btn btn-xs btn-lg", style="margin: 15px;">
  <%= link_to f.title, article_path(f) %></li>
</div>
<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    Copyright &copy Avi Tillu
  </footer>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <li role="separator" class="divider"></li>
            
            <% Category.all.each do |c| %>
            <li style="text-transform: capitalize;"><%= link_to c.name, category_path(c) %> </li>
            <% end %>
            <li role="separator" class="divider"></li>
            
            <% if logged_in? && current_user.admin? %>
            <li><%= link_to "New Category", new_category_path %></li>
            <% end %>
            
          </ul>
        </li>
   
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
        <li><%= link_to "Log Out",logout_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= "(Admin)" if current_user.admin? %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your Profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View Profile", user_path(current_user) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        
        <% else %>
        <li><%= link_to "Log In",login_path %></li>
        <li><%= link_to "Sign Up",signup_path %></li>
        
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
Copyright 2017

<%= render 'layouts/navigation' %>

  <% flash.each do |name, msg| %>

<ul>

<li><%= msg %></li>

</ul>

<% end %>

<div class="container">
  <%= yield %>
</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/pages/about.html.erb
<body style="background-color:powderblue;">
<h1>About Us</h1>
<%= link_to 'Home', root_path %>
</body>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 style="color: black; font-weight: bold; padding: 50px 25px; text-align: center;"> Alpha Blog</h1>
  <p><%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %></p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/_userarticles.html.erb
<% @user.articles.each do |a| %>
  
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
    <div style="font-size: 1.7em; text-transform: capitalize; padding-top:50px; padding-bottom: 10px;">
    <%= link_to a.title, article_path(a) %>
    </div>
      <div class="indexdesc">
      <%= truncate(a.description, length: 100) %>
        <div class=article-meta-details>
        <small>Created By: <%= a.user.username if a.user %>,
                <%= time_ago_in_words(a.created_at) %> ago</small>
        </div>
      </div>
        <% if logged_in? && current_user==@user %>
        <div class="article-actions">
        <%= link_to 'Edit', edit_article_path(a), class: "btn btn-xs btn-success" %>
        <%= link_to 'Delete', article_path(a), method: :delete, class: "btn btn-xs btn-danger" %>
        </div>
        <% end %>
      
    </div>
  </div>
  
  <% end %>

app/views/users/edit.html.erb
<h1 style="padding-bottom:15px;font-size:2.1em; border-bottom:1px solid;">Update User Details</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h3 style="color:dimgray; font-size:1.7em; font-weight:bold; text-align:center;">Registered Users</h3></br>
<div align="center">
<%= will_paginate %>
</div>
  <% @users.each do |a| %>
  
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div style="padding-bottom: 10px;">
      <%= link_to gravatar_for(a), user_path(a) %>
      </div>
      <div style="text-transform: capitalize; font-size: 1.3em; padding-bottom: 10px;">
      <%= link_to a.username, user_path(a) %>
      </div>
      <div class="indexdesc" style="color:dimgray;">
      <%= a.email %>
      </div>
        <% if logged_in? && (current_user==a || current_user.admin?) %>
        <div class="article-actions">
        <%= link_to 'Edit', edit_user_path(a), class: "btn btn-xs btn-success" %>
        <%= link_to 'Delete', user_path(a), method: :delete, class: "btn btn-xs btn-danger", 
        data: { confirm: "Are you sure?" } %>
        </div>
        <% else %>
        <div class="article-actions">
        <%= link_to "View", user_path(a), class: "btn btn-xs btn-success" %>
        </div>
        <% end %>
      
    </div>
  </div>
  
  <% end %>

app/views/users/new.html.erb
<h1 style="padding-bottom:10px; font-size:2.1em; border-bottom: 1px solid">Create User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h3 style="text-transform: capitalize;"> Welcome to <%= @user.username %>'s page</h3>
<p id="notice"><%= notice %></p>

<%= gravatar_for @user %>

<p style="padding-top: 10px;">
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p></br>

<h4 style="border-bottom: 1px solid; text-transform: capitalize;"><%= @user.username %>'s articles</h4></br>

<div align="center">
<%= will_paginate @user_articles %>
</div>

<%= render 'userarticles' %>

<div align="center">
<%= will_paginate @user_articles %>
</div>

<div class="article-actions">
<% if logged_in? && (current_user==@user || current_user.admin?) %>
<%= link_to 'Edit User', edit_user_path(@user), class: "btn btn-xs btn-success" %> |
<%= link_to 'Delete User', user_path(@user), method: :delete, class: "btn btn-xs btn-danger" %> |
<% end %>
<%= link_to 'Back to Users', users_path, class: "btn btn-xs btn-success" %>
</div>